#!/bin/bash
#Bash script to remote control a plex client

player="127.0.0.1" #player to use
server="192.168.60.102" #server to use
action=''

function sendcmd () {
		curl -s "http://$server:32400/system/players/$player/$controller/$action"
}

case "$1" in
	help)
		echo "Usage: plexcmd [Command] [Optional Arguments]"
		echo "Commands:"
		echo "	control"
		echo "	get_clients"
		echo "	navigate [option]"
		echo "	playback [option]"
		echo "	notify [text]"
		echo "	pause"
		echo "	setvolume [1-100]"
		;;
	control)
		interactive=1;
	;;
	get_clients) #List the connected clients
		curl -s "http://$server:32400/clients"
		;;
	navigate) #Navigation commands
		controller="navigation"
		if [[ "$2" == "interactive" ]]; then
			interactive=1
		else
			action="$2"
		fi
		if [[ -z "$2" ]]; then
			echo "Commands:"
			echo "	$(tput setaf 1)interactive$(tput sgr0)"
			echo "	moveUp"
			echo "	moveDown"
			echo "	moveLeft"
			echo "	moveRight"
			echo "	pageUp"
			echo "	pageDown"
			echo "	nextLetter"
			echo "	previousLetter"
			echo "	select"
			echo "	back"
			echo "	contextMenu"
			echo "	toggleOSD"
		fi
		;;
	playback) #Playback commands
		controller="playback"
		action="$2"
		if [[ -z "$2" ]]; then
			echo "Commands:"
			echo "	play"
			echo "	pause"
			echo "	stop"
			echo "	rewind"
			echo "	fastForward"
			echo "	stepForward"
			echo "	bigStepForward"
			echo "	stepBack"
			echo "	bigStepBack"
			echo "	skipNext"
			echo "	skipPrevious"
		fi
		;;
	notify) #Send a notification
		controller="application"
		#escape passed in argument
		value=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$2")
		action="sendString?text=$value"
		;;
	getsessions)
		curl -s "http://$server:32400/status/sessions"
		;;
	getprefs)
		curl -s "http://$server:32400/:/prefs"
	;;	
	pause) #Pause playback
		controller="playback"
		action="pause"
		;;
	setvolume) #Set the volume
		controller="application"
		#value=$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$2")
		action="setVolume?level=$2"
		;;
	*)
		echo "Unrecognized command. Use plexcmd help for usage details."
		;;
esac

#Interactive mode
if [[ "$interactive" == "1" ]]; then
	echo "Arrow keys to navigate"
	echo "Enter to select"
	# keys
	au="`echo -e '\e[A'`" # arrow up
	ad="`echo -e '\e[B'`" # arrow down
	ar="`echo -e '\e[C'`" # arrow right
	al="`echo -e '\e[D'`" # arrow left
	ec="`echo -e '\e'`"   # escape
	while [[ "$INPUT" != "q" ]]; do
		read -sn1 INPUT
		if [[ "$INPUT" == "$ec" ]];then
			read -sn2 INPUT2
			INPUT="$INPUT$INPUT2";
		fi
		action=""
		case "$INPUT" in
			"$au")
				controller="navigation"
				action="moveUp";
			;;
			"$ar")
				controller="navigation"
				action="moveRight";
			;;
			"$ad")
				controller="navigation"
				action="moveDown";
			;;
			"$al")
				controller="navigation"
				action="moveLeft";
			;;
			"")
				controller="navigation"
				action="select";
			;;
			"")
				controller="navigation"
				action="back";
			;;
			"-")
				controller=""
				action=""
			;;
			"=")
				controller=""
				action=""
			;;
			q)
				exit 0;
			;;
			*)
				echo "Button not recognized."	
			;;
		esac
		sendcmd
		echo "$action"
	done
else
	if [ -n "$action" ]; then
		url="http://$server:32400/system/players/$player/$controller/$action"
		#debug echo
		echo $action
		echo $url
		curl -s $url
	fi
fi
